Repository PDA-ARMAGYETDON/pda-armagyetdon-backend, pull requests merged in 2024-09, with the labels that each got.

#108 채팅 리팩토링
  chatting/build.gradle
  chatting/src/main/java/com/example/chatting/controller/ChatRoomController.java
  chatting/src/main/java/com/example/chatting/dto/ChatMessageResponse.java
  chatting/src/main/java/com/example/chatting/service/ChatRoomService.java
Labels: enhancement

#74 매매 제안에 투표하고 매매 주문으로 넘어가는 로직 구현
  common/src/main/java/com/example/common/auth/AuthInterceptor.java
  common/src/main/java/com/example/common/exception/ErrorCode.java
  group-investment/src/main/java/com/example/group_investment/auth/filter/JwtFilter.java
  group-investment/src/main/java/com/example/group_investment/config/SecurityConfig.java
  group-investment/src/main/java/com/example/group_investment/member/Member.java
  group-investment/src/main/java/com/example/group_investment/rabbitMq/RabbitMqConfig.java
  group-investment/src/main/java/com/example/group_investment/tradeOffer/TradeOffer.java
  group-investment/src/main/java/com/example/group_investment/tradeOffer/TradeOfferController.java
  group-investment/src/main/java/com/example/group_investment/tradeOffer/TradeOfferService.java
  group-investment/src/main/java/com/example/group_investment/tradeOffer/TradeOfferVote.java
  group-investment/src/main/java/com/example/group_investment/tradeOffer/TradeOfferVoteRepository.java
  group-investment/src/main/java/com/example/group_investment/tradeOffer/dto/CreateTradeRequest.java
  group-investment/src/main/java/com/example/group_investment/tradeOffer/dto/TradeOfferVoteDto.java
  group-investment/src/main/java/com/example/group_investment/tradeOffer/dto/VoteTradeOfferRequest.java
  group-investment/src/main/java/com/example/group_investment/tradeOffer/dto/VoteTradeOfferResponse.java
  group-investment/src/main/java/com/example/group_investment/tradeOffer/exception/TradeOfferErrorCode.java
  group-investment/src/main/java/com/example/group_investment/tradeOffer/exception/TradeOfferException.java
  group-investment/src/main/java/com/example/group_investment/tradeOffer/utils/TradeOfferCommunicator.java
  group-investment/src/main/java/com/example/group_investment/tradeOffer/utils/TradeOfferConverter.java
  group-investment/src/main/resources/application.yml
  stock-system/src/main/java/com/example/stock_system/account/exception/AccountErrorCode.java
  stock-system/src/main/java/com/example/stock_system/backend_only/BackendController.java
  stock-system/src/main/java/com/example/stock_system/enums/TradeStatus.java
  stock-system/src/main/java/com/example/stock_system/holdings/HoldingsRepository.java
  stock-system/src/main/java/com/example/stock_system/holdings/HoldingsService.java
  stock-system/src/main/java/com/example/stock_system/holdings/exception/HoldingsErrorCode.java
  stock-system/src/main/java/com/example/stock_system/rabbitMq/RabbitMqConfig.java
  stock-system/src/main/java/com/example/stock_system/stocks/StocksController.java
  stock-system/src/main/java/com/example/stock_system/trade/Trade.java
  stock-system/src/main/java/com/example/stock_system/trade/TradeRepository.java
  stock-system/src/main/java/com/example/stock_system/trade/TradeService.java
  stock-system/src/main/java/com/example/stock_system/trade/dto/CreateTradeRequest.java
  stock-system/src/main/java/com/example/stock_system/trade/dto/TradeDto.java
  stock-system/src/main/java/com/example/stock_system/trade/exception/TradeException.java
  stock-system/src/main/resources/application.yml
Labels: enhancement

#120 매매 제안 관련 api에 예외 처리 추가
  group-investment/src/main/java/com/example/group_investment/rabbitMq/RabbitMqConfig.java
  group-investment/src/main/java/com/example/group_investment/tradeOffer/TradeOfferController.java
  group-investment/src/main/java/com/example/group_investment/tradeOffer/TradeOfferService.java
  group-investment/src/main/java/com/example/group_investment/tradeOffer/dto/TradeOfferDto.java
  group-investment/src/main/java/com/example/group_investment/tradeOffer/dto/TradeOfferResponse.java
  group-investment/src/main/java/com/example/group_investment/tradeOffer/exception/TradeOfferErrorCode.java
  group-investment/src/main/java/com/example/group_investment/tradeOffer/utils/TradeOfferCommunicator.java
  group-investment/src/main/java/com/example/group_investment/tradeOffer/utils/TradeOfferConverter.java
  stock-system/src/main/java/com/example/stock_system/backend_only/BackendController.java
  stock-system/src/main/java/com/example/stock_system/holdings/HoldingsController.java
  stock-system/src/main/java/com/example/stock_system/holdings/HoldingsService.java
  stock-system/src/main/java/com/example/stock_system/trade/TradeRepository.java
  stock-system/src/main/java/com/example/stock_system/trade/TradeService.java
  stock-system/src/main/java/com/example/stock_system/trade/dto/GetAllTradesResponse.java
  stock-system/src/main/java/com/example/stock_system/trade/dto/TradeResponse.java
  stock-system/src/main/resources/application.yml
Labels: enhancement

#121 메인페이지(포트폴리오 페이지), 자동 매매 로직 처리
  group-investment/src/main/java/com/example/group_investment/backend_only/BackendController.java
  group-investment/src/main/java/com/example/group_investment/member/MemberRepository.java
  group-investment/src/main/java/com/example/group_investment/team/TeamController.java
  group-investment/src/main/java/com/example/group_investment/team/TeamService.java
  stock-system/build.gradle
  stock-system/src/main/java/com/example/stock_system/account/AccountController.java
  stock-system/src/main/java/com/example/stock_system/account/AccountService.java
  stock-system/src/main/java/com/example/stock_system/account/dto/GetTeamAccountResponse.java
  stock-system/src/main/java/com/example/stock_system/holdings/Holdings.java
  stock-system/src/main/java/com/example/stock_system/holdings/HoldingsController.java
  stock-system/src/main/java/com/example/stock_system/holdings/HoldingsService.java
  stock-system/src/main/java/com/example/stock_system/holdings/dto/HoldingsDto.java
  stock-system/src/main/java/com/example/stock_system/realTimeStock/RealTimeStockController.java
  stock-system/src/main/java/com/example/stock_system/realTimeStock/RealTimeStockService.java
  stock-system/src/main/java/com/example/stock_system/trade/TradeService.java
Labels: enhancement

#122 Swagger Authorizaton 확인 추가 + email, Id 중복체크 API 추가
  ag-gateway/src/main/java/com/example/ag_gateway/authorization/JwtFilter.java
  ag-gateway/src/main/java/com/example/ag_gateway/config/SecurityConfig.java
  ag-gateway/src/main/java/com/example/ag_gateway/config/WebConfig.java
  common/src/main/java/com/example/common/auth/AuthInterceptor.java
  common/src/main/java/com/example/common/auth/JwtUtil.java
  common/src/main/java/com/example/common/config/SwaggerConfig.java
  group-investment/src/main/java/com/example/group_investment/auth/AuthController.java
  group-investment/src/main/java/com/example/group_investment/auth/AuthService.java
  group-investment/src/main/java/com/example/group_investment/auth/filter/JwtFilter.java
  group-investment/src/main/java/com/example/group_investment/config/SecurityConfig.java
  group-investment/src/main/java/com/example/group_investment/user/User.java
  group-investment/src/main/java/com/example/group_investment/user/UserController.java
  group-investment/src/main/java/com/example/group_investment/user/UserRepository.java
  group-investment/src/main/java/com/example/group_investment/user/UserService.java
  group-investment/src/main/java/com/example/group_investment/user/dto/ValidEmailRequest.java
  group-investment/src/main/java/com/example/group_investment/user/dto/ValidIdRequest.java
  group-investment/src/main/java/com/example/group_investment/user/exception/UserErrorCode.java
Labels: bug, documentation, enhancement

#123 규칙 제안 조회 isVote와id추가 , 규칙 제안 투표 로직 수정
  group-investment/src/main/java/com/example/group_investment/ruleOffer/RuleOfferController.java
  group-investment/src/main/java/com/example/group_investment/ruleOffer/RuleOfferService.java
  group-investment/src/main/java/com/example/group_investment/ruleOffer/dto/GetROfferResponseDisband.java
  group-investment/src/main/java/com/example/group_investment/ruleOffer/dto/GetROfferResponsePayFee.java
  group-investment/src/main/java/com/example/group_investment/ruleOffer/dto/GetROfferResponseUpvoteNumber.java
  group-investment/src/main/java/com/example/group_investment/ruleOffer/dto/GetROfferResponseUrgentSale.java
  group-investment/src/main/java/com/example/group_investment/ruleOfferVote/RuleOfferVoteController.java
  group-investment/src/main/java/com/example/group_investment/ruleOfferVote/RuleOfferVoteRepository.java
  group-investment/src/main/java/com/example/group_investment/ruleOfferVote/RuleOfferVoteService.java
Labels: bug, enhancement

#126 pending 상태 팀 초대코드 조회, 유저가 속한 팀 정보 조회 api에 ( 카테고리, 이름) 추가
  group-investment/src/main/java/com/example/group_investment/member/dto/MemberDto.java
  group-investment/src/main/java/com/example/group_investment/team/InvitationRepository.java
  group-investment/src/main/java/com/example/group_investment/team/TeamController.java
  group-investment/src/main/java/com/example/group_investment/team/TeamService.java
  group-investment/src/main/java/com/example/group_investment/team/dto/DetailPendingTeamResponse.java
  group-investment/src/main/java/com/example/group_investment/team/dto/TeamByUserResponse.java
Labels: enhancement

#128 대시보드 정보 조회 api 생성(주요 증권 뉴스 Top5, 코스피/코스닥 지수)
  invest-references/build.gradle
  invest-references/src/main/java/com/example/invest_references/InvestRefController.java
  invest-references/src/main/java/com/example/invest_references/InvestRefService.java
  invest-references/src/main/java/com/example/invest_references/dto/Kosdaq.java
  invest-references/src/main/java/com/example/invest_references/dto/Kospi.java
  invest-references/src/main/java/com/example/invest_references/dto/MarketIndexResponse.java
  invest-references/src/main/java/com/example/invest_references/dto/News.java
  invest-references/src/main/java/com/example/invest_references/exception/InvestRefErrorCode.java
  invest-references/src/main/java/com/example/invest_references/exception/InvestRefException.java
Labels: enhancement

#130 투표 진행 중인 매매 제안 조회
  group-investment/src/main/java/com/example/group_investment/tradeOffer/TradeOfferController.java
  group-investment/src/main/java/com/example/group_investment/tradeOffer/TradeOfferRepository.java
  group-investment/src/main/java/com/example/group_investment/tradeOffer/TradeOfferService.java
  group-investment/src/main/java/com/example/group_investment/tradeOffer/dto/GetPendingTradeOfferResponse.java
  stock-system/src/main/java/com/example/stock_system/holdings/HoldingsService.java
Labels: enhancement

#133 보유 종목 비율 조회(모임 계좌 포트폴리오)
  stock-system/src/main/java/com/example/stock_system/account/exception/AccountErrorCode.java
  stock-system/src/main/java/com/example/stock_system/holdings/HoldingsController.java
  stock-system/src/main/java/com/example/stock_system/holdings/HoldingsService.java
  stock-system/src/main/java/com/example/stock_system/holdings/dto/GetHoldingsRatioResponse.java
Labels: enhancement

#137 채팅 모듈에서 teamId를 통해 유저 list뽑아오는 로직 추가
  alarm/src/main/resources/application.yml
  chatting/src/main/java/com/example/chatting/config/RestTemplateConfig.java
  chatting/src/main/java/com/example/chatting/controller/ChatRoomController.java
  chatting/src/main/java/com/example/chatting/service/ChatRoomService.java
  group-investment/src/main/java/com/example/group_investment/backend_only/BackendController.java
  group-investment/src/main/java/com/example/group_investment/team/TeamService.java
  group-investment/src/main/resources/application.yml
  stock-system/src/main/java/com/example/stock_system/account/AccountService.java
  stock-system/src/main/resources/application.yml
Labels: enhancement

#138 대시보드 data추가
  invest-references/src/main/java/com/example/invest_references/InvestRefController.java
  invest-references/src/main/java/com/example/invest_references/InvestRefService.java
  invest-references/src/main/java/com/example/invest_references/config/IgnoreSSL.java
  invest-references/src/main/java/com/example/invest_references/config/RestTemplateConfig.java
  invest-references/src/main/java/com/example/invest_references/dto/ShinhanData.java
  invest-references/src/main/java/com/example/invest_references/exception/InvestRefErrorCode.java
  stock-system/src/main/java/com/example/stock_system/account/AccountService.java
Labels: enhancement

#141 매매 거래 내역 조회
  stock-system/src/main/java/com/example/stock_system/trade/TradeController.java
  stock-system/src/main/java/com/example/stock_system/trade/TradeRepository.java
  stock-system/src/main/java/com/example/stock_system/trade/TradeService.java
  stock-system/src/main/java/com/example/stock_system/trade/dto/GetAllTradesResponse.java
  stock-system/src/main/java/com/example/stock_system/trade/dto/GetTradeResponse.java
Labels: enhancement

#131 회원가입, 내정보수정, jwt 토큰업데이트
  ag-gateway/src/main/java/com/example/ag_gateway/authorization/JwtFilter.java
  ag-gateway/src/main/java/com/example/ag_gateway/config/SecurityConfig.java
  common/src/main/java/com/example/common/config/WebConfig.java
  group-investment/src/main/java/com/example/group_investment/auth/AgUserDetailsService.java
  group-investment/src/main/java/com/example/group_investment/auth/AuthController.java
  group-investment/src/main/java/com/example/group_investment/auth/filter/LoginFilter.java
  group-investment/src/main/java/com/example/group_investment/backend_only/BackendController.java
  group-investment/src/main/java/com/example/group_investment/config/SecurityConfig.java
  group-investment/src/main/java/com/example/group_investment/enums/JoinStatus.java
  group-investment/src/main/java/com/example/group_investment/enums/TeamStatus.java
  group-investment/src/main/java/com/example/group_investment/enums/UserStatus.java
  group-investment/src/main/java/com/example/group_investment/member/Member.java
  group-investment/src/main/java/com/example/group_investment/rule/exception/RuleErrorCode.java
  group-investment/src/main/java/com/example/group_investment/ruleOffer/RuleOfferController.java
  group-investment/src/main/java/com/example/group_investment/ruleOffer/RuleOfferService.java
  group-investment/src/main/java/com/example/group_investment/team/Team.java
  group-investment/src/main/java/com/example/group_investment/team/TeamController.java
  group-investment/src/main/java/com/example/group_investment/team/TeamService.java
  group-investment/src/main/java/com/example/group_investment/team/dto/CreateTeamResponse.java
  group-investment/src/main/java/com/example/group_investment/team/dto/ParticipateResponse.java
  group-investment/src/main/java/com/example/group_investment/team/dto/PayFail.java
  group-investment/src/main/java/com/example/group_investment/user/User.java
  group-investment/src/main/java/com/example/group_investment/user/UserController.java
  group-investment/src/main/java/com/example/group_investment/user/UserRepository.java
  group-investment/src/main/java/com/example/group_investment/user/UserService.java
  group-investment/src/main/java/com/example/group_investment/user/dto/GetUserResponse.java
  group-investment/src/main/java/com/example/group_investment/user/dto/SignUpRequest.java
  group-investment/src/main/java/com/example/group_investment/user/dto/UpdateRequest.java
  group-investment/src/main/java/com/example/group_investment/user/dto/UpdateResponse.java
  group-investment/src/main/java/com/example/group_investment/user/dto/UserDto.java
  group-investment/src/main/java/com/example/group_investment/user/exception/UserErrorCode.java
Labels: enhancement

#145 로그인 시 탈퇴 사용자 검증
  group-investment/src/main/java/com/example/group_investment/auth/AgUserDetailsService.java
  group-investment/src/main/java/com/example/group_investment/auth/filter/LoginFilter.java
  group-investment/src/main/java/com/example/group_investment/user/User.java
  group-investment/src/main/java/com/example/group_investment/user/UserController.java
  stock-system/src/main/java/com/example/stock_system/transferHistory/TransferHistoryController.java
Labels: enhancement

#147 규칙 제안 조회, 추가 request맵핑 rule-offer 추가
  group-investment/src/main/java/com/example/group_investment/rule/RuleController.java
  group-investment/src/main/java/com/example/group_investment/rule/RuleService.java
  group-investment/src/main/java/com/example/group_investment/ruleOffer/RuleOfferController.java
Labels: enhancement

#149 gateway 서버 라우팅 경로 추가
  ag-gateway/src/main/java/com/example/ag_gateway/authorization/JwtFilter.java
  ag-gateway/src/main/java/com/example/ag_gateway/config/RouteConfig.java
  chatting/src/main/java/com/example/chatting/service/ChatRoomService.java
  common/src/main/java/com/example/common/auth/AuthInterceptor.java
  group-investment/src/main/java/com/example/group_investment/auth/filter/JwtFilter.java
  group-investment/src/main/java/com/example/group_investment/backend_only/BackendController.java
  group-investment/src/main/java/com/example/group_investment/tradeOffer/utils/TradeOfferCommunicator.java
  stock-system/src/main/java/com/example/stock_system/account/AccountService.java
  stock-system/src/main/java/com/example/stock_system/backend_only/BackendController.java
Labels: enhancement

#151 이메일 검증 로직 수정
  group-investment/src/main/java/com/example/group_investment/user/UserRepository.java
  group-investment/src/main/java/com/example/group_investment/user/UserService.java
  group-investment/src/main/java/com/example/group_investment/user/exception/UserErrorCode.java
Labels: bug

#135 랭킹 조회 api 구현
  group-investment/src/main/java/com/example/group_investment/ranking/Ranking.java
  stock-system/src/main/java/com/example/stock_system/account/AccountController.java
  stock-system/src/main/java/com/example/stock_system/account/AccountRepository.java
  stock-system/src/main/java/com/example/stock_system/account/AccountService.java
  stock-system/src/main/java/com/example/stock_system/account/TeamAccountRepository.java
  stock-system/src/main/java/com/example/stock_system/enums/Category.java
  stock-system/src/main/java/com/example/stock_system/ranking/Ranking.java
  stock-system/src/main/java/com/example/stock_system/ranking/RankingController.java
  stock-system/src/main/java/com/example/stock_system/ranking/RankingRepository.java
  stock-system/src/main/java/com/example/stock_system/ranking/RankingService.java
  stock-system/src/main/java/com/example/stock_system/ranking/dto/RankingDto.java
  stock-system/src/main/java/com/example/stock_system/ranking/dto/SelectRankingResponse.java
  stock-system/src/main/java/com/example/stock_system/ranking/dto/SelectRankingWithTeamResponse.java
  stock-system/src/main/java/com/example/stock_system/ranking/exception/RankingErrorCode.java
  stock-system/src/main/java/com/example/stock_system/ranking/exception/RankingException.java
Labels: enhancement

#158 헬스체크 api 통과
  ag-gateway/src/main/java/com/example/ag_gateway/authorization/JwtFilter.java
  common/src/main/java/com/example/common/auth/AuthInterceptor.java
  group-investment/src/main/java/com/example/group_investment/auth/AuthController.java
  group-investment/src/main/java/com/example/group_investment/auth/filter/JwtFilter.java
Labels: enhancement

#166 메인 머지
  .gitignore
  alarm/src/main/java/com/example/alarm/firebase/FcmService.java
  alarm/src/main/java/com/example/alarm/firebase/dto/ChatAlarmDto.java
  alarm/src/main/java/com/example/alarm/firebase/dto/VoteToAlarmDto.java
  alarm/src/main/java/com/example/alarm/rabbitMq/RabbitMqConfig.java
  alarm/src/main/resources/application.yml
  chatting/src/main/java/com/example/chatting/config/WebSocketConfig.java
  group-investment/src/main/java/com/example/group_investment/auth/AuthController.java
  group-investment/src/main/java/com/example/group_investment/auth/dto/UpdateTokenResponse.java
  group-investment/src/main/java/com/example/group_investment/rabbitMq/MqSender.java
  group-investment/src/main/java/com/example/group_investment/ruleOffer/RuleOfferService.java
  group-investment/src/main/java/com/example/group_investment/ruleOffer/dto/VoteRuleToAlarmDTO.java
  group-investment/src/main/java/com/example/group_investment/ruleOffer/exception/RuleOfferException.java
  group-investment/src/main/java/com/example/group_investment/tradeOffer/TradeOfferService.java
  group-investment/src/main/java/com/example/group_investment/tradeOffer/dto/VoteStockToAlarmDto.java
  group-investment/src/main/resources/application.yml
Labels: enhancement

#168 채팅 에러 해결
  alarm/.gitignore
  alarm/src/main/java/com/example/alarm/rabbitMq/RabbitMqConfig.java
  group-investment/src/main/java/com/example/group_investment/GroupInvestmentApplication.java
  group-investment/src/main/java/com/example/group_investment/ruleOffer/dto/VoteRuleToAlarmDto.java
Labels: bug

#169 채팅 모듈과 증권 시스템 모듈에 헬스체크 api 추가
  ag-gateway/src/main/java/com/example/ag_gateway/authorization/JwtFilter.java
  chatting/src/main/java/com/example/chatting/controller/ChatRoomController.java
  stock-system/src/main/java/com/example/stock_system/stocks/StocksController.java
Labels: enhancement

#170 메인에 머지
  ag-gateway/src/main/java/com/example/ag_gateway/authorization/JwtFilter.java
  alarm/.gitignore
  alarm/src/main/java/com/example/alarm/rabbitMq/RabbitMqConfig.java
  chatting/src/main/java/com/example/chatting/controller/ChatRoomController.java
  group-investment/src/main/java/com/example/group_investment/GroupInvestmentApplication.java
  group-investment/src/main/java/com/example/group_investment/ruleOffer/dto/VoteRuleToAlarmDto.java
  stock-system/src/main/java/com/example/stock_system/stocks/StocksController.java
Labels: enhancement

#171 FCM서비스 키 경로 등록
  alarm/src/main/resources/application.yml
Labels: enhancement

#152 팀 폭파 조건 만족시 폭파하는 로직 작성
  group-investment/src/main/java/com/example/group_investment/backend_only/BackendController.java
  group-investment/src/main/java/com/example/group_investment/rule/RuleService.java
  group-investment/src/main/java/com/example/group_investment/rule/dto/CheckDisband.java
  stock-system/src/main/java/com/example/stock_system/account/AccountController.java
  stock-system/src/main/java/com/example/stock_system/account/AccountService.java
  stock-system/src/main/java/com/example/stock_system/account/dto/CheckDisband.java
Labels: enhancement

#153 처음에 돈 못낸 애들 방출하도록 처리
  stock-system/src/main/java/com/example/stock_system/account/AccountService.java
Labels: enhancement

#172 팀을 생성할때 랭킹에 data가 추가되도록 수정
  chatting/src/main/java/com/example/chatting/service/ChatRoomService.java
  group-investment/src/main/java/com/example/group_investment/backend_only/BackendController.java
  group-investment/src/main/java/com/example/group_investment/team/TeamService.java
  stock-system/src/main/java/com/example/stock_system/account/AccountController.java
  stock-system/src/main/java/com/example/stock_system/account/AccountService.java
  stock-system/src/main/java/com/example/stock_system/ranking/Ranking.java
  stock-system/src/main/java/com/example/stock_system/ranking/RankingController.java
  stock-system/src/main/java/com/example/stock_system/ranking/RankingService.java
Labels: enhancement

#155 팀 펜딩 상태일때 조회 api 에서 참여안한 user 의 경우 member not found 뜨는 오류 수정
  group-investment/src/main/java/com/example/group_investment/team/TeamService.java
Labels: bug

#162 랭킹 업데이트하게 수정
  stock-system/src/main/java/com/example/stock_system/account/AccountController.java
  stock-system/src/main/java/com/example/stock_system/account/AccountService.java
  stock-system/src/main/java/com/example/stock_system/ranking/RankingRepository.java
  stock-system/src/main/java/com/example/stock_system/ranking/RankingService.java
Labels: enhancement

#175 User Get API URI 수정해드렸읍니다
  group-investment/src/main/java/com/example/group_investment/backend_only/BackendController.java
  group-investment/src/main/java/com/example/group_investment/user/UserController.java
  group-investment/src/main/java/com/example/group_investment/user/UserService.java
Labels: enhancement

#176 팀 계좌 조회시 보유 종목이 없으면 0 값으로 출력하도록 처리
  stock-system/src/main/java/com/example/stock_system/account/AccountController.java
  stock-system/src/main/java/com/example/stock_system/account/AccountService.java
  stock-system/src/main/java/com/example/stock_system/realTimeStock/RealTimeStockService.java
Labels: enhancement

#181 url 형식 변경
  invest-references/src/main/java/com/example/invest_references/InvestRefController.java
Labels: enhancement

#187 사용자 비밀번호 변경 api 생성
  group-investment/src/main/java/com/example/group_investment/user/UserController.java
  group-investment/src/main/java/com/example/group_investment/user/UserPInfo.java
  group-investment/src/main/java/com/example/group_investment/user/UserPInfoService.java
  group-investment/src/main/java/com/example/group_investment/user/dto/UpdatePasswordRequest.java
Labels: enhancement

#188 대시보드 API 병합+invest-ref서버라우팅변경+GET규칙제안이름추가
  ag-gateway/src/main/java/com/example/ag_gateway/config/RouteConfig.java
  group-investment/src/main/java/com/example/group_investment/ruleOffer/RuleOfferService.java
  group-investment/src/main/java/com/example/group_investment/ruleOffer/dto/GetROfferResponseDisband.java
  group-investment/src/main/java/com/example/group_investment/ruleOffer/dto/GetROfferResponsePayFee.java
  group-investment/src/main/java/com/example/group_investment/ruleOffer/dto/GetROfferResponseUpvoteNumber.java
  group-investment/src/main/java/com/example/group_investment/ruleOffer/dto/GetROfferResponseUrgentSale.java
  invest-references/src/main/java/com/example/invest_references/InvestRefController.java
  invest-references/src/main/java/com/example/invest_references/InvestRefService.java
  invest-references/src/main/java/com/example/invest_references/dto/GetIssueResponse.java
Labels: enhancement

#189 메인 Merge/배포하겠습니다.
  ag-gateway/src/main/java/com/example/ag_gateway/config/RouteConfig.java
  chatting/src/main/java/com/example/chatting/config/WebSocketConfig.java
  chatting/src/main/java/com/example/chatting/controller/ChatRoomController.java
  chatting/src/main/java/com/example/chatting/service/ChatRoomService.java
  group-investment/src/main/java/com/example/group_investment/backend_only/BackendController.java
  group-investment/src/main/java/com/example/group_investment/ruleOffer/RuleOfferService.java
  group-investment/src/main/java/com/example/group_investment/ruleOffer/dto/GetROfferResponseDisband.java
  group-investment/src/main/java/com/example/group_investment/ruleOffer/dto/GetROfferResponsePayFee.java
  group-investment/src/main/java/com/example/group_investment/ruleOffer/dto/GetROfferResponseUpvoteNumber.java
  group-investment/src/main/java/com/example/group_investment/ruleOffer/dto/GetROfferResponseUrgentSale.java
  group-investment/src/main/java/com/example/group_investment/team/TeamService.java
  group-investment/src/main/java/com/example/group_investment/user/UserController.java
  group-investment/src/main/java/com/example/group_investment/user/UserPInfo.java
  group-investment/src/main/java/com/example/group_investment/user/UserPInfoService.java
  group-investment/src/main/java/com/example/group_investment/user/dto/UpdatePasswordRequest.java
  invest-references/src/main/java/com/example/invest_references/InvestRefController.java
  invest-references/src/main/java/com/example/invest_references/InvestRefService.java
  invest-references/src/main/java/com/example/invest_references/dto/GetIssueResponse.java
  stock-system/src/main/java/com/example/stock_system/ranking/RankingController.java
Labels: enhancement

#198 중복된 의존성 제거 및 commons-logging 제거
  alarm/build.gradle
Labels: bug

#197 계좌 조회 api 분리(DB에 있는 값 불러오는 api)
  stock-system/src/main/java/com/example/stock_system/account/AccountController.java
  stock-system/src/main/java/com/example/stock_system/account/AccountService.java
  stock-system/src/main/java/com/example/stock_system/account/dto/GetPersonalAccountResponse.java
  stock-system/src/main/java/com/example/stock_system/account/dto/GetTeamAccountResponse.java
Labels: enhancement

#195 배치 파일 추가 및 파일 수정
  ag-gateway/src/main/java/com/example/ag_gateway/config/RouteConfig.java
  group-investment/src/main/java/com/example/group_investment/backend_only/BackendController.java
  group-investment/src/main/java/com/example/group_investment/team/Team.java
  group-investment/src/main/java/com/example/group_investment/team/TeamService.java
  stock-system/src/main/java/com/example/stock_system/account/AccountController.java
  stock-system/src/main/java/com/example/stock_system/account/AccountService.java
  stock-system/src/main/java/com/example/stock_system/holdings/HoldingsService.java
  stock-system/src/main/java/com/example/stock_system/holdings/dto/ClosingPirceRequest.java
  stock-system/src/main/java/com/example/stock_system/stocks/StocksController.java
  stock-system/src/main/java/com/example/stock_system/stocks/StocksRepository.java
  stock-system/src/main/java/com/example/stock_system/stocks/StocksService.java
Labels: enhancement

#199 페이지네이션으로 이체 내역 보내줄 때 transferDate를 기준으로 최신순으로 정렬
  stock-system/src/main/java/com/example/stock_system/account/AccountController.java
  stock-system/src/main/java/com/example/stock_system/transferHistory/TransferHistoryController.java
  stock-system/src/main/java/com/example/stock_system/transferHistory/TransferHistoryService.java
Labels: enhancement

#201 장 마감 후 데이터 처리 & 스톡 코드 참조 형식 변경
  stock-system/src/main/java/com/example/stock_system/account/AccountController.java
  stock-system/src/main/java/com/example/stock_system/account/AccountService.java
  stock-system/src/main/java/com/example/stock_system/askPrice/AskPriceService.java
  stock-system/src/main/java/com/example/stock_system/realTimeStock/RealTimeStockService.java
  stock-system/src/main/java/com/example/stock_system/stocks/StocksService.java
Labels: enhancement

#204 Stock, Chat 서버 따로 cors 처리
  ag-gateway/src/main/java/com/example/ag_gateway/config/RouteConfig.java
  ag-gateway/src/main/resources/application.yml
  alarm/src/main/java/com/example/alarm/config/WebConfig.java
  chatting/src/main/java/com/example/chatting/config/WebConfig.java
  common/src/main/java/com/example/common/auth/AuthInterceptor.java
  common/src/main/java/com/example/common/auth/JwtUtil.java
  group-investment/src/main/java/com/example/group_investment/config/WebConfig.java
  invest-references/src/main/java/com/example/invest_references/config/WebConfig.java
  stock-system/src/main/java/com/example/stock_system/config/WebMvcConfig.java
  stock-system/src/main/resources/application.yml
Labels: enhancement

#207 stock health check (필터 제외) 경로 수정
  ag-gateway/src/main/java/com/example/ag_gateway/authorization/JwtFilter.java
  common/src/main/java/com/example/common/auth/AuthInterceptor.java
  group-investment/src/main/java/com/example/group_investment/auth/filter/JwtFilter.java
Labels: enhancement
